language: d

#compiler:
#  - dmd

install:
  # dmd
  - DMD_VER=2.066.0
  - DMD=dmd_${DMD_VER}-0_amd64.deb
  - DUB_VER=0.9.22-rc.2
  - DUB=dub-${DUB_VER}-linux-x86_64
  - NODE_VER=v0.10.31
  - NODE=node-${NODE_VER}-linux-x64
  - wget http://downloads.dlang.org/releases/2014/${DMD}
  - sudo dpkg -i ${DMD} || true
  - sudo apt-get -y update
  - sudo apt-get -fy install
  - sudo dpkg -i ${DMD}
  # dub
  - wget http://code.dlang.org/files/${DUB}.tar.gz
  - sudo tar -C /usr/local/bin -zxf ${DUB}.tar.gz
  # linenoise
  - curl -sSL https://github.com/antirez/linenoise/archive/master.tar.gz | tar -zxf -
  - (cd linenoise-master && cc -shared -fPIC linenoise.c -o liblinenoise.so)
  - sudo install -t /usr/lib/x86_64-linux-gnu linenoise-master/liblinenoise.so
  # yuglify
  - wget http://nodejs.org/dist/${NODE_VER}/${NODE}.tar.gz
  - tar -zxf ${NODE}.tar.gz
  - sudo ${NODE}/bin/npm install -g yuglify
  - export PATH=${NODE}/bin:${PATH}

script:
  # run unittests for library
  - git submodule update
  - dub test
  # test building all other configurations
  - dub build -c console
  - dub build -c sandbox
  - dub build -c server
